name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint_and_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run eslint
        run: yarn lint
        env:
          CI: true
      - name: Run unit tests
        run: yarn test
        env:
          CI: true
      - name: Run build to spot typescript errors
        run: yarn build
        env:
          CI: true
